### ISSUE TITLE
Resize team member pictures

### ISSUE THREAD

**Issue by katrinacrisostomo** [uwblueprint/website#11]
since they're 140 x 140, 280 x 280 should be good. TY, sorry I should've done it from the beginning.

**Comment by bryanc208** [comment]
We had a quick chat on Slack.. but I'm still unsure about what you mean by this. I think you meant that we want the images to be higher resolution.. but without taking higher quality originals this can't really be achieved. They may not look as good as they did originally because the images had to be compressed (we were loading 4~5MB of images before compressing).

**Comment by bryanc208** [comment]
Closing this for now until we get clarification.
