### ISSUE TITLE
[Student Application] Isn't a message suppose to be appear in the slack channel

### ISSUE THREAD

**Issue by chrisjluc** [uwblueprint/website#43]
I submitted an application and slack wasn't pinged

**Comment by aaronte** [comment]
@bryanc208 We talked about this. Either we subscribe to firebase's paid tier and do this EASILY. OR we can use AWS lamdba which I asked if you can set up and I'll configure.

**Comment by bryanc208** [comment]
Ok, I can set up Lambda tonight. How do you need it set up? Also, @chrisjluc we need an AWS account to do this or we can start paying for Firebase. Up to you. I think paying for Firebase also comes with added benefits like more load capacity and storage/db capacity as well.

**Comment by aaronte** [comment]
Id recommend paying because our infrastructure will be hosted in one place and it won't be that expensive since it's "pay as you go". We need this paid service to contact non-google services in the cloud (I.e. slack)

**Comment by chrisjluc** [comment]
What are the costs exactly? I'm looking here:
https://firebase.google.com/pricing/

If it's just to contact non-google services in the cloud it doesn't seem
that necessary, like posting in slack. We could survive without it.

I'm worried that we would hit the limits on the free tier, but it seems
okay because we can back up / remove data from the cloud.

**Comment by bryanc208** [comment]
Okay, then let's ditch the notifications and plan to have a person dedicated to checking the admin panel on a daily basis (can be a rotation). We likely want to stick to the convention that an application of status 'Pending' is one that has not been touched in any way so those would be considered new applications. We should move those from status 'Pending' to some other status acknowledge that we've received it and so that we can distinguish those from new applications that we receive later on.
