### ISSUE TITLE
[Task] Investigate missing applications from prod db

### ISSUE THREAD

**Issue by hkjayakumar** [uwblueprint/website#67]
As of 29th March, there were applications from 

1. Hassan Altaf
2. Some guy in ALL CAPS
3. Another name which I forget

These applications are now missing from the prod db.

**Comment by hkjayakumar** [comment]
Update from @chrisjluc :

@bryanc208  messaged me last night saying while moving one of the applicants who was in dev to prod, something funky happened where prod data got deleted. He's digging into this as we speak as it's super high priority. He's going to likely contact support and attempt to retrieve their application. The estimated impact is we're missing 3 - 4 applications.

**Comment by chrisjluc** [comment]
Message from @bryanc208 :
>hey so really bad news
first, are all the applications in the dev db the same as the ones that are on the prod db?
I think they are..? so in the process of moving over Ryan Perry Nyugen's application, something funky happened and the prod db's student applications got blown away
i think i've recovered most of them since they all seemed to be replicated in the dev db but seems like we're missing 1

Message from me:
> Oh i see let me see
we're missing at least 3
maybe 4
they looked like they were different to me
is there no way to retrieve the data?
well i guess shit happens, that's kind of unfortunate 😞
i guess we have to think about what to do now about the lost applicants
are there logs maybe that we can look through, i dunno
http://stackoverflow.com/questions/35954986/restore-database-in-firebase
?
http://grokbase.com/t/gg/firebase-talk/1549bdcf57/firebase-recovering-deleted-data
last time i looked at prod there were 10 or 11, but in dev there are like 8
How come new applicants are being put into dev now?
man we should like back up all our firebase users and retrieve the backups of just right before the change was made
i'm sure you can figure it out
let me know if you need anything

**Comment by bryanc208** [comment]
I will email the firebase support team tomorrow and see what they say. However, I suspect we may not be able to do anything as this is a paid feature.

**Comment by chrisjluc** [comment]
Moving forward we should make backups of our database when we're pushing new features to prod or conducting risky tasks.  (Have you made a back up yet?)

It seems like we've lost 2 applicants for sure, because at least one applicant we can get back there data.

Again, @bryanc208 is there no way to retrieve the lost data?

**Comment by bryanc208** [comment]
From what I can tell, there are no logs that are persisted (or none that we have access to) for the database transactions. Furthermore, any backups that Firebase does maintain are outside of our access due to the fact that we do not pay for that service.

We did not create any backups of the database and there are currently no options to automatically create backups through the Firebase console. The best we can do is perhaps set up a job to periodically backup the database in our own format. 

To reiterate, the only option at this point seems to be to email Firebase support and to see if they can do a one-off restore from their periodic backups that they allegedly make behind the scenes. I will follow up once we receive a response.

**Comment by chrisjluc** [comment]
We can manually download our database right?

**Comment by bryanc208** [comment]
Yes, we can export the entire JSON that describes the db from the console: https://console.firebase.google.com/project/uw-blueprint/database/data.

**Comment by chrisjluc** [comment]
I don't think I have access. Can we manually back up to Google Drive every
so often when pushing prod changes or whatever while people are applying?

**Comment by hkjayakumar** [comment]
@chrisjluc Should we contact the first applicant and ask them to re-apply ?

**Comment by chrisjluc** [comment]
Bryan contacted Firebase support and they said they'll be able to restore
our applicants within the next couple days. So I think it should be fine.

**Comment by chrisjluc** [comment]
@bryanc208 any updates? have we recovered the lost applications?

**Comment by hkjayakumar** [comment]
That's great !
Should we backup our existing applicants in case they overwrite them?

**Comment by bryanc208** [comment]
The lost applications have been recovered under the project `uwblueprint-restore`. Haven't got around to merging the applications yet. I backed up last night before requesting the restore and is now stored in `DB Backups` in our Drive.

**Comment by chrisjluc** [comment]
Great, once the restored applications are merged with prod we can close this ticket.

**Comment by bryanc208** [comment]
The 3 missing applications from Hassan Altaf, Lucy Wang, and NIKSHEP SARAVANAN have been restored.
